#!/bin/sh
# Stage page/vendor and page/assets from the pinned sources.
#
# page/vendor and page/assets are NOT committed: every file in them is a
# copy of something the repo already pins authoritatively.
#   - libv86.js / v86.wasm  come from node_modules/v86        (package-lock.json)
#   - xterm.js / xterm.css  come from node_modules/@xterm/xterm (package-lock.json)
#   - seabios.bin / vgabios.bin are the committed blobs in bios/
#   - state-page.bin.gz is regenerated by the two commands at the bottom
# Keeping the pins in the lockfile rather than in copied blobs means there
# is exactly one place a version can be wrong.
#
# Usage: sh tools/stage-page.sh
set -e

cd "$(dirname "$0")/.."

if [ ! -d node_modules/v86 ]; then
  echo "node_modules missing; run: npm ci" >&2
  exit 1
fi

mkdir -p page/vendor page/assets

cp node_modules/v86/build/libv86.js page/vendor/
cp node_modules/v86/build/v86.wasm page/vendor/
cp node_modules/@xterm/xterm/lib/xterm.js page/vendor/
cp node_modules/@xterm/xterm/css/xterm.css page/vendor/
cp bios/seabios.bin page/vendor/
cp bios/vgabios.bin page/vendor/

# The networked tier is the P3b snapshot (bzImage-p4 plus the overlay that
# fixes ICRNL at the console and carries no baked config, so the guest can
# land at temur's own wizard). The P3a and P3a-fix snapshots stay on disk
# as the record of what those keyed runs used; they are simply no longer
# served.
if [ -f build/state-p5-page.bin ]; then
  gzip -9 -c build/state-p5-page.bin > page/assets/state-p5-page.bin.gz
  echo "staged page/assets/state-p5-page.bin.gz (networked tier)"
else
  echo "build/state-p5-page.bin missing; networked tier will not load" >&2
fi

if [ -f build/state-page.bin ]; then
  gzip -9 -c build/state-page.bin > page/assets/state-page.bin.gz
  echo "staged page/assets/state-page.bin.gz (offline tier)"
else
  cat >&2 <<'EOF'
build/state-page.bin missing. Regenerate it with:

  node tools/run-guest.mjs kit/bzImage-p2 build/rootfs-temur.cpio.gz \
       build/steps-page-snap.json 128 build/state-page.bin

(build/rootfs-temur.cpio.gz itself is kit/rootfs.cpio.gz with the
temur overlay appended; see reports/P1.md "Image recipe".)
EOF
  exit 1
fi

echo "staged page/vendor and page/assets"
ls -l page/vendor page/assets
