#!/bin/sh
# Stage page/vendor and page/assets from the pinned sources.
#
# page/vendor is NOT committed: every file in it is a copy of something
# the repo already pins authoritatively. page/assets is a MIXED case, and
# saying "not committed" here was simply false from P3b decision C
# onwards: the two SERVED snapshots are committed so that the deployed
# site is built from the published commit, and everything else under
# page/assets stays out. See .gitignore, which spells out that shape.
#   - libv86.js / v86.wasm  come from node_modules/v86        (package-lock.json)
#   - xterm.js / xterm.css  come from node_modules/@xterm/xterm (package-lock.json)
#   - seabios.bin / vgabios.bin are the committed blobs in bios/
#   - state-p7-net.bin.gz / state-p7-offline.bin.gz are regenerated by
#     the two commands at the bottom
# Keeping the pins in the lockfile rather than in copied blobs means there
# is exactly one place a version can be wrong.
#
# Usage: sh tools/stage-page.sh [--vendor-only]
#
# --vendor-only copies the vendored libraries and BIOS blobs and does NOT
# touch page/assets. That is the mode a Cloudflare Pages build runs in:
# the Pages builder has node and this repository, but not the v86
# harness, the kernel tree or the multi-gigabyte build directory, so it
# cannot regenerate a snapshot and must not try. The snapshots reach the
# deployed site by whichever route the operator rules on (committed .gz
# files, or a direct upload); either way this script's vendor half is the
# only part a Pages build needs.
set -e

VENDOR_ONLY=no
for arg in "$@"; do
  case "$arg" in
    --vendor-only) VENDOR_ONLY=yes ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

cd "$(dirname "$0")/.."

if [ ! -d node_modules/v86 ]; then
  echo "node_modules missing; run: npm ci" >&2
  exit 1
fi

mkdir -p page/vendor page/assets

cp node_modules/v86/build/libv86.js page/vendor/
cp node_modules/v86/build/v86.wasm page/vendor/
cp node_modules/@xterm/xterm/lib/xterm.js page/vendor/
cp node_modules/@xterm/xterm/css/xterm.css page/vendor/
cp bios/seabios.bin page/vendor/
cp bios/vgabios.bin page/vendor/

if [ "$VENDOR_ONLY" = yes ]; then
  echo "staged page/vendor only (--vendor-only); page/assets left alone"
  ls -l page/vendor
  exit 0
fi

# P6: BOTH TIERS COME FROM ONE KERNEL AND ONE OVERLAY NOW. That is the
# structural fix for the defect the page had been papering over: the
# offline snapshot was built from the P2-era rootfs, so console.sh and
# the MOTD only ever reached the networked image, and an operator met
# Enter echoing as ^M on the live page. The page still types stty icrnl
# at landing as belt and braces; it is simply no longer load bearing.
#
# P7 rebuilt this pair on temur v0.34.0 for office-format reading. Only ONE
# pair is staged and committed at a time: the superseded p6 files are removed
# from the working tree in the same commit, and git history is what keeps
# them. Carrying both would double the ~30 MB these blobs already cost.
if [ -f build/state-p7-net.bin ]; then
  gzip -9 -c build/state-p7-net.bin > page/assets/state-p7-net.bin.gz
  echo "staged page/assets/state-p7-net.bin.gz (networked tier)"
else
  echo "build/state-p7-net.bin missing; networked tier will not load" >&2
fi

if [ -f build/state-p7-offline.bin ]; then
  gzip -9 -c build/state-p7-offline.bin > page/assets/state-p7-offline.bin.gz
  echo "staged page/assets/state-p7-offline.bin.gz (offline tier)"
else
  cat >&2 <<'EOF'
build/state-p7-offline.bin missing. Regenerate it with:

  node tools/gen-steps-p7-offline-snap.mjs
  node tools/run-guest.mjs kit/bzImage-p6 build/rootfs-temur-p6.cpio.gz \
       build/steps-p7-offline-snap.json 128 build/state-p7-offline.bin

(build/rootfs-temur-p6.cpio.gz is kit/rootfs.cpio.gz with the p6 overlay
appended; see reports/P6.md "Reproduce". The build REFUSES if the 9p
share is not pristine at the snapshot point.)
EOF
  exit 1
fi

echo "staged page/vendor and page/assets"
ls -l page/vendor page/assets
