// The build stamp: the checkable form of "the deployed relay always
// matches a published commit".
//
// WHY IT IS A GENERATED FILE AND NOT A COMMITTED CONSTANT. A stamp
// written INTO a tracked file changes that file, which changes the
// commit, so the stamp of commit N could only ever be committed in
// commit N+1 and would therefore always be wrong. The committed sources
// carry no sha at all; this script writes two generated files that are
// NOT tracked, and the running page and relay read them. That way the
// stamp is always the commit the build was made from, and there is no
// version of the source that lies.
//
// NO SHA, NO BUILD. If the commit cannot be read, or the tree is dirty
// so the sha would not describe what is actually being shipped, this
// script writes NOTHING and exits nonzero. It never writes "unknown":
// an honest failure is the point, because everything downstream treats
// the stamp as a promise.
//
// Usage: node tools/stamp.mjs [--allow-dirty]
import { execFileSync } from "child_process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const allowDirty = process.argv.includes("--allow-dirty");

function fail(msg) {
  console.error("stamp: REFUSING TO STAMP. " + msg);
  console.error("stamp: nothing was written. Fix the above and run again.");
  process.exit(1);
}

function git(args) {
  return execFileSync("git", args, { cwd: ROOT, encoding: "utf8" }).trim();
}

let commit = null;
let source = null;

// Cloudflare Pages checks the repository out itself and exports the
// commit it built; that is the same promise, from the builder rather
// than from the working tree, and its checkout is by construction clean.
const fromEnv = process.env.CF_PAGES_COMMIT_SHA;
if (fromEnv && /^[0-9a-f]{40}$/.test(fromEnv.trim())) {
  commit = fromEnv.trim();
  source = "CF_PAGES_COMMIT_SHA";
} else {
  try {
    commit = git(["rev-parse", "HEAD"]);
    source = "git rev-parse HEAD";
  } catch (e) {
    fail("cannot read the commit (" + String(e.message).split("\n")[0] + ")");
  }
  if (!/^[0-9a-f]{40}$/.test(commit)) {
    fail("git returned something that is not a commit sha: " + JSON.stringify(commit));
  }
  let dirty = "";
  try {
    dirty = git(["status", "--porcelain"]);
  } catch (e) {
    fail("cannot check whether the tree is clean (" + String(e.message).split("\n")[0] + ")");
  }
  if (dirty && !allowDirty) {
    fail(
      "the working tree is dirty, so " +
        commit.slice(0, 7) +
        " does not describe what would be shipped:\n" +
        dirty +
        "\nCommit or stash first. --allow-dirty exists for local experiments " +
        "only and marks the stamp as dirty; never use it for a deployment.",
    );
  }
  if (dirty) source += " (DIRTY, --allow-dirty)";
}

const info = {
  commit,
  short: commit.slice(0, 7),
  built: new Date().toISOString(),
  source,
};

// The relay reads JSON at startup and answers GET /version from it.
const relayOut = path.join(ROOT, "relay", "build-info.json");
fs.writeFileSync(relayOut, JSON.stringify(info, null, 2) + "\n");

// The page reads a global, so it needs no fetch and no await: index.html
// loads this before app.js.
const pageOut = path.join(ROOT, "page", "build-info.js");
fs.writeFileSync(
  pageOut,
  "// GENERATED by tools/stamp.mjs. Not tracked; do not edit.\n" +
    "window.__BUILD__ = " +
    JSON.stringify(info) +
    ";\n",
);

console.log("stamped " + info.short + " (" + info.source + ")");
console.log("  " + path.relative(ROOT, relayOut));
console.log("  " + path.relative(ROOT, pageOut));
